this is the 3rd milestone pull request
Salvador-ON/03_Tic_Tac_Toe pull request #3
Opened 2020-02-20 16:36 UTC by Salvador-ON

we take of the dry rule

and separate all the logic classes to the lib directory

and we only left in the main.rb the user interaction

2020-02-20 20:04 UTC, shshamim63 reviewed
## Status :spades: Required Changes :spades: 
___
Hi @Salvador-ON and @Dandush03 :wave: ,
Awesome initiative :clap: . I can see a lot of classes in this project. But some issue are blocking me to approve this project. So please follow the instructions to complete this project.
___
### :clubs: [Mandatory Changes] :clubs: 
___
1. All the puts should be placed in main.rb file . But I can see some of them in game.rb file. Please check the comment below.
2. Well when a user place an invalid move he should get a message that it is invalid. And you project is doing it. But the problem is when I try to choose an occupied move it provides me a message about invalid move, after that if I place a valid move it alters the value of the invalid position where I tried to make a move.
![image](https://user-images.githubusercontent.com/38625956/74973095-0e753a00-544d-11ea-8799-145f4998ee69.png)
![image](https://user-images.githubusercontent.com/38625956/74973144-1fbe4680-544d-11ea-906f-aa3e009492b4.png)
![image](https://user-images.githubusercontent.com/38625956/74973191-34024380-544d-11ea-8168-f7b3b80f180a.png)
![image](https://user-images.githubusercontent.com/38625956/74974120-d7078d00-544e-11ea-98b6-b7023e45e8ac.png)
![image](https://user-images.githubusercontent.com/38625956/74973260-51cfa880-544d-11ea-9b8b-23140b16b8bc.png)
It should not work like that. If a person place an invalid move it should render it. And if that player places a valid move it should store that.
___
### :space_invader: Optional :space_invader: 
___
1. A self documented code is the key to make your project more preferable. Cause If a contributor can not guess the task of a variable and function based on its name, it will be marked as a low readable code. So the more you will make your variable, method name meaningful it will become more readable.
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

2020-02-20 20:04 UTC, shshamim63 commented on lib/game.rb
> +    @t = 0
#### [Optional]
To make your program more readable, what I believe, code should be self documenting. Which means you don't have to explain every single line because every identifier (variable, method, class) has a clear semantic name. Now look at the marked lines, how am I suppose to know the purpose of this variable without debugging the code. It decreases the readability of the code. So it would be better if you rename the variables to a meaningful name.

2020-02-20 20:04 UTC, shshamim63 commented on lib/game.rb
> +  end
##### Mandatory
No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-02-20 20:24 UTC, Salvador-ON commented
we fix all the mandatory issues

2020-02-20 23:52 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: :clap: However, the code needs further refactoring in order to get approval for the milestone. Check :arrow_down: 

- **[REQUIRED]** Use attr_readers/attr_writers instead of attr_accessors. The student must be aware that by using it they allow writing that property from outside the class. That variable can be set to anything. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  - You have used `attr_accessor` in many classes :skull:  For each attribute var in your classes, you should think if you should expose them in **Read only** mode or **Write only** mode because it's unsafe to expose them in **full access** mode.

- **[OPTIONAL]** You should opt for using more meaningful names for your variable, It demystifies the code for strangers who want benefit from your code.

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
_**Ahmed Mahfoudh**_

2020-02-21 15:10 UTC, Salvador-ON commented
we fix the attribute_accesor to use only when we really need it

2020-02-21 22:57 UTC, Anna-Myzukina commented
### Good job! :+1: 

## Status [Approved]

* Good job on rectifying the issues raised in the previous reviews  :100: 
#### Go ahead and merge to master.
#### Goodluck in your next project Happy coding <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"><img class="emoji" alt="computer" height="25" width="25" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"></g-emoji>

2020-02-21 22:57 UTC, Anna-Myzukina approved these changes

2020-02-21 23:14 UTC, merged

2020-02-26 13:50 UTC, Salvador-ON commented on lib/game.rb
> +    @t = 0
thanks we will take this in consideration for the nexts projects